name: 'Greeting action'
description: 'Greets someone from a container'
author: '@Kasper1985'

inputs:
  name:
    description: 'Who to greet'
    default: 'world'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.name }}
