name: 'My Container Action'
description: 'Get started with container actions'
author: '@Kasper1985'
inputs:
  person:
    description: 'Who to greet'
    default: 'world'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.person }}
