name: Environment workflow

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    env:
      ENV_SECRET: ${{ secrets.MY_ENV_SECRET }}
      REPO_SECRET: ${{ secrets.MY_REPO_SECRET }}
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Show environment variable
        run: echo ${{ vars.MY_ENV_VAR }}

      - name: Show repo variable
        run: echo ${{ vars.MY_REPO_VAR }}

      - name: Show environment secret
        run: |
          echo ${{ secrets.MY_ENV_SECRET }}
          echo $ENV_SECRET

      - name: Show repo secret
        run: |
          echo ${{ secrets.MY_REPO_SECRET }}
          echo $REPO_SECRET
